### signalling conditions #####################################################
library(rlang)

# 1. Write a wrapper around file.remove() that throws an error if the file to
# be deleted does not exist.

file.remove2 <- function(f) {
    if (!file.exists(f)) {
        stop("file does not exist")
    }
    file.remove(f)
}

# 2. What does the appendLF argument to message() do? How is it related to
# cat()?

# ANS:
# from message():
# appendLF: logical: should messages given as a character string
#                    have a newline appended?

# to do this with `cat()`, you'd need to provide the `"\n"` as a string, or as
# a `sep` argument 

### handling conditions #######################################################
# 1. What extra information does the condition generated by abort() contain
# compared to the condition generated by stop() i.e. what’s the difference
# between these two objects? Read the help for ?abort to learn more.

str(catch_cnd(stop("An error")))
str(catch_cnd(abort("An error"))) # you can supply any extra meta data. 
                                  # by default, the whole traceback is given

# 2. Predict the results of evaluating the following code

show_condition <- function(code) {
  tryCatch(
    error = function(cnd) "error",
    warning = function(cnd) "warning",
    message = function(cnd) "message",
    {
      code
      NULL
    }
  )
}

show_condition(stop("!"))
# "error"
show_condition(10)
# NULL
show_condition(warning("?!"))
# "warning"
show_condition({
  10
  message("?")
  warning("?!")
})
# "message"

# 3. Explain the results of running this code: ANS: too difficult...

withCallingHandlers(
  message = function(cnd) message("b"),
  withCallingHandlers(
    message = function(cnd) message("a"),
    message("c")
  )
)
#> b
#> a
#> b
#> c

# 4. Read the source code for catch_cnd() and explain how it works.
# ANS: wrapper around tryCatch. If the code throws a specific condition, the
# class of the condition is returned.

# 5. How could you rewrite show_condition() to use a single handler?
show_condition2 <- function(code) {
    tryCatch(
             attributes(
                        catch_cnd(code)
                        )[["class"]][2])
}

show_condition2(stop("!"))
# "error"
show_condition2(10)
# NULL
show_condition2(warning("?!"))
# "warning"
show_condition2({
  10
  message("?")
  warning("?!")
})
# "message"

### custom conditions #########################################################

### applications ##############################################################
